AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  lambdatag:
    Type: String
    Default: live
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      AutoPublishAlias: !Ref lambdatag
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
